sudo: required 
os: linux
services:
  - docker
env:
  global:
      - GIT_SHA=$(git rev-parse HEAD)
      - CLOUDSDK_CORE_DISABLE_PROMPTS=1
      # disable user input prompt
before_install:
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  # install Google CDK and souces its commands to Shell
  - gcloud components update kubectl
  # install and update kubectl via google clodu
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  # retrieve encrpyted credentials from travis/git
  - gcloud auth activate-service-account --key-file service-account.json
  # activate auth with google cloud via service-account.json file
  - gcloud config set project multi-k8s-326908
  - gcloud config set compute/zone asia-east1-c
  - gcloud container clusters get-credentials multi-k8s
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t gowithkk/react-test -f ./client/Dockerfile.dev ./clinet
  # build the test image

script:
    - docker run gowithkk/react-test npm test -- --coverage

deploy:
  provider: script
  # get travis to run the script on the master branch
  script: bash ./deploy.sh
  on:
    branch: master
