sudo: required 
os: linux
services:
  - docker
before_install:
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  # install Google CDK and souces its commands to Shell
  - gcloud components update kubectl
  # install and update kubectl via google clodu
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  # retrieve encrpyted credentials from travis/git
  - gcloud auth activate-service-account --key-file service-account.json
  # activate auth with google cloud via service-account.json file